### ISSUE TITLE
GUI glitches on dataset creation

### ISSUE THREAD

**Issue by stigviaene** [hopshadoop/hopsworksFrontend#38]
Upon creation of a DataSet:
* The page listing the DataSets should be updated automatically.
* The growl message should only mention the project-relative path, not the absolute HDFS path. (So if you are in project **projectX** and you create DataSet **DSA**, the message should read something like "A folder /DSA was created.")

**Comment by ErmiasG** [comment]
the message comes from the back-end so I am moving this issue to the back-end

**Comment by ErmiasG** [comment]
first point is implemented, second point moved to https://github.com/hopshadoop/hopsworks/issues/30
